seed = 8

[model]
iterations = 4000
early_stopping_rounds = 3999
od_pval = 0.001
bagging_temperature = 0.3110699487549791
depth = 7
l2_leaf_reg = 9.511495661368633
leaf_estimation_iterations = 7
learning_rate = 0.028800235043744016
task_type = "CPU"
thread_count = 4

[fit]
logging_level = "Verbose"

[data]
seed = 0
path = ":data/homecredit-default"
cache = true
split = "default"
cat_policy = "ordinal"
